title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
include: ["_pages-en", _pages-is, _pages-pl]
collections:
  pages-en:
    output: true
    permalink: /en/:path
  pages-is:
    output: true
    permalink: /:path
  pages-pl:
    output: true
    permalink: /pl/:path
  articles:
    output: true
    permalink: /folkid/greinar/:path/
  representatives:
    output: true
  administration:
    output: true
  associations:
    output: true
  staff:
    output: true
defaults:
  -
    scope:
      path: "_pages-is"
    values:
      lang: is
  -
    scope:
      path: "_pages-en"
    values:
      lang: en
  -
    scope:
      path: _pages-pl
    values:
      lang: pl
  -
    scope:
      path: ""
      type: posts
    values:
      banner: true
      lang: is
  -
    scope:
      path: ""
      type: articles
    values:
      banner: true
      lang: is
  -
    scope:
      path: "_representatives"
    values:
      layout: representative
      banner: true
      lang: is
      permalink: /folkid/:title/
      representatives_page: /folkid
      see_more: true
  -
    scope:
      path: "_representatives/en"
    values:
      layout: representative
      banner: true
      lang: en
      permalink: /en/representatives/:path/
      representatives_page: /pl/representatives
  -
    scope:
      path: "_representatives/pl"
    values:
      layout: representative
      banner: true
      lang: pl
      permalink: /pl/representatives/:path/
      representatives_page: /pl/representatives
  -
    scope:
      path: "_associations"
    values:
      layout: association
      lang: is
      permalink: /adildarfelog/:title/
  -
    scope:
      path: "_associations/en"
    values:
      permalink: /en/assoications/:title/
      lang: en
      layout: association
  -
    scope:
      path: "_staff"
    values:
      lang: is
      category: staff
  -
    scope:
      path: "_staff/en"
    values:
      lang: en
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
