title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
include: ["_pages"]
collections:
  pages:
    output: true
    permalink: /:path
  articles:
    output: true
    permalink: /fulltruar/greinar/:path/
  administration:
    output: true
defaults:
  -
    scope:
      path: "_pages"
    values:
      lang: is
  -
    scope:
      path: _pages/en
    values:
      lang: en
  -
    scope:
      path: _pages/pl
    values:
      lang: pl
  -
    scope:
      path: ""
      type: posts
    values:
      banner: true
  -
    scope:
      path: ""
      type: articles
    values:
      banner: true
  -
    scope:
      path: ""
      layout: representative
    values:
      banner: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
