title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
include: ["_pages", _pages-is]
collections:
  pages:
    output: true
    permalink: /:path
  pages-is:
    output: true
    permalink: /:path
  articles:
    output: true
    permalink: /fulltruar/greinar/:path/
  administration:
    output: true
  associations:
    output: true
defaults:
  -
    scope:
      path: "_pages-is"
    values:
      lang: is
  -
    scope:
      path: _pages/en
    values:
      lang: en
  -
    scope:
      path: _pages/pl
    values:
      lang: pl
  -
    scope:
      path: ""
      type: posts
    values:
      banner: true
  -
    scope:
      path: ""
      type: articles
    values:
      banner: true
  -
    scope:
      path: ""
      layout: representative
    values:
      banner: true
  -
    scope:
      path: "_associations"
    values:
      layout: association
      lang: is
      permalink: /adildarfelog/:path/
  -
    scope:
      path: "_associations/en"
    values:
      permalink: /en/assoications/:path/
      lang: en
      layout: association
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
