title: Píratar
description: Vefsíða Pírata
baseurl:
sass:
  sass_dir: _scss
  style: compressed
t:
  is:
    share_event: Deila með vini
    add_to_calendar: Setja í dagatal
    register_event: Skrá mig á viðburð
  en:
    share_event: Share with a friend
    add_to_calendar: Add to calendar
    register_event: Register
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
