title:
  is: Píratar
  en: Icelandic Pirate Party
description:
  is: Vefsíða Pírata
  en: Icelandi Pirate Party website
baseurl:
sass:
  sass_dir: _scss
  style: compressed
collections:
  events:
    output: true
t:
  is:
    see_event: Skoða viðburð
  en:
    see_event: Read more