---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: directory
  path: _pages-is
  label: Pages - IS
  create: all
  match: "**/*"
- type: directory
  path: _pages-en
  label: Pages - EN
  create: all
  match: "**/*"
- type: directory
  path: _pages-pl
  label: Pages - PL
  create: all
  match: "**/*"
- type: directory
  path: _associations
  label: Aðildarfélög
  create: all
  match: "**/*"
- type: directory
  path: _representatives
  label: Fulltrúar
  create: documents
  match: "**/*"
  templates:
  - representative
- type: directory
  path: _administration
  label: Stjórn
  create: documents
  match: "**/*"
  templates:
  - stjornarmadur
- type: directory
  path: _staff
  label: Starfsfólk
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Configuration
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
