---
label: Menus-Config
hide_body: true
fields:
- type: field_group
  name: about-pirates
  label: about-pirates
  fields:
  - type: text
    name: is
    label: is
  - type: text
    name: en
    label: en
- type: field_group
  name: policies
  label: policies
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: is
    label: is
- type: field_group
  name: events
  label: events
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: is
    label: is
- type: field_group
  name: tortuga
  label: tortuga
  fields:
  - type: text
    name: en
    label: en
  - type: text
    name: is
    label: is
